services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8089:80"
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - pg-network

  keycloak-postgres:
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql
    networks:
      - pg-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      KEYCLOAK_ADMIN_CLIENT_ID: web-admin-serviceaccount
      KEYCLOAK_BOOTSTRAP_MODE: ${KEYCLOAK_BOOTSTRAP_MODE:-off}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_LOG_LEVEL: debug
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/8080'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/providers:/opt/keycloak/providers
      - ./keycloak/imports:/opt/keycloak/data/import
    depends_on:
      - keycloak-postgres
    networks:
      - pg-network

  keycloak-config:
    image: adorsys/keycloak-config-cli:latest
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      IMPORT_FILES_LOCATIONS: /config/*
      KEYCLOAK_BOOTSTRAP_MODE: ${KEYCLOAK_BOOTSTRAP_MODE:-off}
      IMPORT_VARS_ENABLED: "true"
      IMPORT_VAR_PREFIX: ""
    volumes:
      - ./keycloak/config:/config:ro
    command: >
      sh -c '
        if [ "$KEYCLOAK_BOOTSTRAP_MODE" = "off" ]; then
          echo "Keycloak is healthy. Applying declarative config...";
          java -jar /opt/keycloak-config-cli.jar;
        else
          echo "Bootstrap mode on, skipping declarative import";
        fi
      '
    networks:
      - pg-network

volumes:
  postgres_data:
  keycloak_postgres_data:

networks:
  pg-network:
    driver: bridge
