<Project Sdk="Godot.NET.Sdk/4.5.1">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<RootNamespace>rpggame</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <Folder Include="Resources\Units\" />
	</ItemGroup>

	<!-- Project References 
	<ItemGroup>
		<PackageReference Include="Google.Protobuf" />
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Grpc.Tools">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\libs\dotnet\core\application\CheeseGrater.Dotnet.Core.Application.csproj" />
		<ProjectReference Include="..\..\..\libs\dotnet\core\domain\CheeseGrater.Dotnet.Core.Domain.csproj" />
		<ProjectReference Include="..\..\..\libs\dotnet\core\infrastructure\CheeseGrater.Dotnet.Core.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\libs\dotnet\services\rpg-api\application\CheeseGrater.Dotnet.Services.RpgApi.Application.csproj" />
		<ProjectReference Include="..\..\..\libs\dotnet\services\rpg-api\domain\CheeseGrater.Dotnet.Services.RpgApi.Domain.csproj" />
		<ProjectReference Include="..\..\..\libs\dotnet\services\rpg-api\infrastructure\CheeseGrater.Dotnet.Services.RpgApi.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\..\..\libs\contracts\gamecommands.proto" GrpcServices="Client" ></Protobuf>
	</ItemGroup>
	-->

</Project>
